apiVersion: v1
kind: Namespace
metadata:
  name: lab-vibe
---
# Base de Dados PostgreSQL
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: lab-vibe
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: arm64v8/postgres:15-alpine
        env:
        - name: POSTGRES_PASSWORD
          value: "pass"
---
# A API Vibe
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vibe-api
  namespace: lab-vibe
spec:
  selector:
    matchLabels:
      app: vibe-api
  template:
    metadata:
      labels:
        app: vibe-api
    spec:
      containers:
      - name: api
        image: python:3.11-slim
        ports:
        - containerPort: 8000
---
# POLÍTICA ZERO TRUST (A Proteção)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-external-db
  namespace: lab-vibe
spec:
  podSelector:
    matchLabels:
      app: postgres
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: vibe-api # APENAS a API pode falar com a BD