name: DevSecOps-Vibe-Audit
on: [push, pull_request]

jobs:
  trivy-scan:
    name: Security Auditor
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4 # Versão mais recente

      - name: Auditoria de Segurança Completa
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          # AQUI ESTÁ O SEGREDO: Ativamos explicitamente os 3 scanners
          scanners: 'vuln,secret,misconfig' 
          severity: 'CRITICAL,HIGH,MEDIUM'
          format: 'table'
          exit-code: '1' # Falha o pipeline se encontrar erros HIGH/CRITICAL